import { runGeminiTest } from "@/ai/gemini";
import { runGroqTest } from "@/ai/groq";
import { runOpenCodeZen } from "@/ai/opencode";
import { NextRequest, NextResponse } from "next/server";

export async function POST(req: NextRequest) {
    try {
        const { prompt } = await req.json();

        if (!prompt || !prompt.trim()) {
            return NextResponse.json({ error: "Prompt is required." }, { status: 400 });
        }
        if (prompt.length > 2000) {
            return NextResponse.json({ error: "Prompt must be under 2000 characters." }, { status: 400 });
        }

        const baseModelSystemPrompt = "Your response must be short, concise, direct, and to the point. Avoid extra conversational filler or fluff.";

        // 1. Fetch responses from all three models in parallel
        const [geminiResponse, groqResponse, deepseekResponse] = await Promise.all([
            runGeminiTest(prompt, baseModelSystemPrompt),
            runGroqTest(prompt, baseModelSystemPrompt),
            runOpenCodeZen(prompt, baseModelSystemPrompt, "deepseek-v4-flash-free"),
        ]);

        // 2. Define the system prompt for the evaluator
        const systemPrompt = `
        You are an expert AI evaluator and content synthesizer.
        Your task is to analyze responses to a user's prompt generated by three different AI models.
        Compare the three responses, identify which one got which parts right, note any contradictions or inaccuracies, and merge the strongest elements into a single, cohesive, and comprehensive final response.

        Guidelines:

        - Do not mention the names of the models (e.g., "Model 1", "Gemini", "Groq") or that you are evaluating other AI outputs.

        - Present the final answer directly, naturally, and professionally as if it were your own primary response.

        - Improve readability, flow, and structural formatting (use lists, bold text, or code blocks if appropriate).`;

        // 3. Format the evaluation prompt containing the responses
        const evaluationPrompt = `
                User Prompt: "${prompt}"

                AI Model Responses to synthesize:
                ---
                Response 1:
                ${geminiResponse}
                ---
                Response 2:
                ${groqResponse}
                ---
                Response 3:
                ${deepseekResponse}
                ---
                        `;

        // 4. Generate the final refined response
        const finalResponse = await runOpenCodeZen(evaluationPrompt, systemPrompt, "nemotron-3-ultra-free");

        console.log("-----------------------------------------------------------------")
        console.log("Gemini Response:", geminiResponse);
        console.log("-----------------------------------------------------------------")
        console.log("Groq Response:", groqResponse);
        console.log("-----------------------------------------------------------------")
        console.log("DeepSeek Response:", deepseekResponse);
        console.log("-----------------------------------------------------------------")
        console.log("-----------------------------------------------------------------")
        console.log("Final Response:", finalResponse);
        console.log("-----------------------------------------------------------------")

        return NextResponse.json({
            gemini: geminiResponse,
            groq: groqResponse,
            deepseek: deepseekResponse,
            finalAnswer: finalResponse
        });

    } catch (error) {
        console.error("Chat route error:", error);
        return NextResponse.json({ error: "Failed to generate response" }, { status: 500 });
    }
}
